version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=foodsquare
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432'
  web:
    image: subangkar/foodsquare
    command: sh -c "while ! nc -z db 5432; do sleep 1; done; ./startdatabase.sh && python3 manage.py runserver 0.0.0.0:8050"
    ports:
      - '8050:8050'
    depends_on:
      - db
    volumes:
    #  - ./your_project_directory:/app  # This maps your project directory to /app in the container
      - .:/app  # This maps your project directory to /app in the container
# docker-compose up
# docker-compose run web python3 manage.py migrate